version: "3.8"

services:
  gpt4all_api:
    image: gpt4all_api
    container_name: gpt4all_api
    restart: always #restart on error (usually code compilation from save during bad state)
    ports:
      - "4891:4891"
    env_file:
      - .env
    environment:
      - APP_ENVIRONMENT=dev
      - WEB_CONCURRENCY=2
      - LOGLEVEL=debug
      - PORT=4891
      - model=${MODEL_BIN} # using variable from .env file
      - inference_mode=cpu
    volumes:
      - './gpt4all_api/app:/app'
      - './gpt4all_api/models:/models' # models are mounted in the container
    command: ["/start-reload.sh"]